### ISSUE TITLE
Store text output from ASV

### ISSUE THREAD

**Issue by ev-br** [OpenMathLib/BLAS-Benchmarks#10]
Text output is currently hidden in the Actions tab --- click Actions, click on a benchmark run, expand the "Run benchmarks" part, scroll down to the output. 

There is a time limit on how long the logs are stored by github, so do we want to save them somewhere?

Note that all benchmark results from all runs are stored in the `results/machine-name/commit-hash.json` files in the `gh-pages` branch, so they are not lost either way.

**Comment by martin-frbg** [comment]
_If_ all the relevant benchmark data ends up in the gh-pages branch , there is probably no need to archive the full logs ?

**Comment by ev-br** [comment]
Indeed they are, and here's a quick-and-dirty  example of reading them in: https://github.com/OpenMathLib/BLAS-Benchmarks/blob/main/analyze.results.example.ipynb
