### ISSUE TITLE
create a PAT for the workflows to push

### ISSUE THREAD

**Issue by ev-br** [OpenMathLib/BLAS-Benchmarks#3]
I'm trying to recreate the workflow of https://github.com/OpenMathLib/OpenBLAS/pull/4751#issuecomment-2169574159 , only with a gh-pages branch instead of a separate publisher repository.
The key point is for a workflow to push benchmark results to a branch --- and this needs a personal access token.

@martin-frbg could you please create and add a PAT? In my fork, the following permissions worked: actions r/w; commit statuses r/w; contents r/w; workflows r/w

**Comment by martin-frbg** [comment]
Sorry, getting a bit lost in the Settings interface for Organizations. I _think_ you should be able to create the PAT yourself now, with me only having to approve your request.

**Comment by ev-br** [comment]
If I'm reading https://stackoverflow.com/questions/75044318/create-personal-access-token-request-for-organization right, the key is to select Resource owner to be the OpenMathLib org.
And I don't seem to be able to.
And _ISTM_ this is limited on the membership level. For comparison, I only see in the Resource owner dropdown only Quansight and Quansight labs --- whatever level I have in the SciPy org is not enough? So definitely just collaboration level access on a single repo in the OpenMathLib does not cut it, sadly.

**Comment by martin-frbg** [comment]
Hmm, confusing. I have now added a fine-grained PAT with the requested permissions; for some reason I cannot appear to extend its validity beyond one year.

**Comment by ev-br** [comment]
Thank you Martin! Could you add the PAT to the repo as a secret and tell me the secret's name?
If you prefer to move the conversation to email, I'm evgeny.burovskiy@gmail

**Comment by ev-br** [comment]
Aaaaand, we're live: http://www.openmathlib.org/BLAS-Benchmarks/
The sources are in the gh-pages branch of this repository: https://github.com/OpenMathLib/BLAS-Benchmarks/tree/gh-pages

Thank you Martin! I wonder what's the best way to remember to renew the token in a year's time. 

This is for x86_64, runnig it on a graviton is https://github.com/OpenMathLib/BLAS-Benchmarks/issues/4
