### ISSUE TITLE
install cirun for this repository

### ISSUE THREAD

**Issue by ev-br** [OpenMathLib/BLAS-Benchmarks#4]
graviton jobs run on the main OpenBLAS repo, but not on this one: https://github.com/OpenMathLib/BLAS-Benchmarks/actions/runs/9549517327/job/26319258806 is stuck on _Waiting for a runner to pick up this job..._ 

I asked Amit https://github.com/aktech of cirun.io, and his reply is

> If you're adding a new runner in the same account ... install cirun for that repository and create a .cirun.yml in the repository to trigger runs.

So I copy-pasted the .cirun.yml from the OpenBLAS repository, and.. it's not enough, so I guess the I'd need to ask @martin-frbg to install cirun for the repository?

**Comment by martin-frbg** [comment]
should be installed already - however, right as I checked the configuration it asked me to add a new permission so that cirun.yml could be read. So maybe it is working already, now that I granted that permission ?

**Comment by ev-br** [comment]
Well, the job at https://github.com/OpenMathLib/BLAS-Benchmarks/actions/runs/9550767014/job/26323517279 is still waiting to be picked up by a runner. 
The workflow file is https://github.com/OpenMathLib/BLAS-Benchmarks/blob/main/.github/workflows/run_cirun_graviton.yml and the `.cirun.yml` is https://github.com/OpenMathLib/BLAS-Benchmarks/blob/main/.cirun.yml

**Comment by martin-frbg** [comment]
removed and re-added the repo to Cirun, and cancelled and reran the job again - now it runs but fails due to not finding an appropriate openblas-scipy32

**Comment by ev-br** [comment]
**Thank you!**
scipy-openblas32 hiccup was due to numpy 2.0 released yesterday. Will probably fix itself on the next scipy-openblas32 rebuild. Meanwhile capping numpy<2 seems to work, and I can proceed fixing the build/upload stage now.
